Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -106,6 +106,39 @@ jobs:
                 # Display the content of aux.txt
                 cat aux.txt
 
+                # Parse diff
+                hunk_header=$(grep -o '@@ [^@]* @@' <<< "$diff")
+                if [[ $hunk_header =~ @@\ -([0-9]+),([0-9]+)\ \+([0-9]+),([0-9]+)\ @@ ]]; then
+                  original_start_line="${BASH_REMATCH[1]}"
+                  original_line_count="${BASH_REMATCH[2]}"
+                  new_start_line="${BASH_REMATCH[3]}"
+                  new_line_count="${BASH_REMATCH[4]}"
+                  echo "Original Start Line: $original_start_line"
+                  echo "Original Line Count: $original_line_count"
+                  echo "New Start Line: $new_start_line"
+                  echo "New Line Count: $new_line_count"
+                else
+                  echo "Failed to parse hunk header"
+                  exit 1
+                fi
+    
+                hunk_lines=$(awk '/@@ [^@]* @@/ { found = 1; next } found { print }' <<< "$diff")
+                line_number=0
+                while IFS= read -r diff_line; do
+                  ((line_number++))
+                  if [[ $diff_line == -* ]]; then
+                    side="LEFT"
+                    start_line=$original_start_line
+                    line=$((original_start_line + line_number - 1))
+                    start_side="LEFT"
+                  elif [[ $diff_line == +* ]]; then
+                    side="RIGHT"
+                    start_line=$new_start_line
+                    line=$((new_start_line + line_number - 1))
+                    start_side="RIGHT"
+                  fi
+                done <<< "$hunk_lines"
+
                 escaped_comments=$(echo "$(cat aux.txt)" | jq -s -R -r @json)
                 curl -s -L \
                 -X POST \
@@ -113,7 +146,7 @@ jobs:
                 -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
                 -H "X-GitHub-Api-Version: 2022-11-28" \
                 https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
-                -d "{\"body\":$escaped_comments}"
+                -d "{\"body\":$escaped_comments, \"commit_id\":\"$commit_id\", \"path\":\"${file_names[-1]}\", \"start_line\":$start_line, \"start_side\":\"$start_side\", \"line\":$line, \"side\":\"$side\"}"
                 
                 > aux.txt
             fi
